name: Build

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: src

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build for release
      run: msbuild src\EthernetHotspot.sln -t:rebuild -property:Configuration=Release /property:Platform=x64

    - name: Package installer
      run: iscc.exe src\installer.iss

    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: installer
        path: src\Installer\EthernetExplorer-Installer.exe

  create_release:
    name: Create Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download installer artifact
      uses: actions/download-artifact@v2
      with:
        name: installer
        path: src\Installer

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          src\Installer\EthernetExplorer-Installer.exe
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        release_name: EthernetHotspot ${{ github.ref }}
        body: ''
